---
title: "Blender: Create a 3D tiled floor"
hero_image: images/banner.png
description: Create a 3D tile in Blender then use Array modifiers to make a full floor
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
- title: You will make
- title: Create your first tile
  completion:
  - engaged
- title: Make a tiled floor
- title: Set the centre point
- title: Quick quiz
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: Use your tiled floor in Unity
  completion:
  - internal
- title: Use your new skills in Blender
  completion:
  - external
