---
title: Blender - Create a 3D tiled floor
hero_image: images/banner.png
description: Create a 3D tile then use array modifiers to make a full floor
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: You will make
- title: Create your first tile
- title: Make a tiled floor
- title: Set the floor centre
- title: Quick quiz
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: Use your tiled floor in Unity
- title: Use your new skills in Blender
